### PR TITLE
settimeout e timeout minimo de 5

### PR DESCRIPTION
**Pull request by guilhermetavares**
treat api down

### CODE REVIEW

**Comment by richard-flosi** [comment]
This or something like it would be useful as I've seen a few `HTTPException: Deadline exceeded while waiting for HTTP response from URL` errors.

**Comment by tysonclugg** [comment]
We're currently having issues with timeouts, and I believe that this PR might help us to alleviate the problem.  We're seeing an `SSLError: The read operation timed out` exception.
selection_417

**Comment by katharosada** [comment]
Hey, I didn't realise this was still causing problems since the PR is from 2015. I'll have a look.

**Comment by katharosada** [comment]
This PR is superseded by 18acc1b26b02b2d40c378faad144202aa5c6be54
Thanks for submitting it! It was a great help.

**Pull request closed without merging**
