### PR TITLE
Feat/python3 update

### PR DESCRIPTION
**Pull request by djstein**
Huge Update. Getting back to PEP 8 formatting, remove relative imports, support for Python 3. Leaving my name as author on this branch due to possibility it will never get merged and it being used in our production.

### CODE REVIEW

**Comment by stewartjarod** [comment]
This would be great :+1:

**Comment by jdennes** [comment]
I don't use this library, and don't really maintain it either. It is supposed to be [officially supported](https://www.campaignmonitor.com/api/wrappers/) by Campaign Monitor.

These changes look good to me though, and I'm happy to merge this since I still can. If you want a faster response to contributions like this in future, I would recommend contacting Campaign Monitor [support](https://help.campaignmonitor.com/contact/) about the maintenance plan for libraries like this.

@djstein Thanks for making this better, and you can expect a new release shortly.

**Comment by jdennes** [comment]
Release: https://github.com/campaignmonitor/createsend-python/releases/tag/v4.2.2

**Comment by xfxf** [comment]
There appears to be a problem with this release.  Can't install 4.2.2 on 3.6.2 on OS X, or 3.4.2 on Linux.  pypi shows 'Unknown' as latest version - https://pypi.python.org/pypi/createsend/4.2.2 

Same issue:

`p# pip3 install createsend==4.2.2
Collecting createsend==4.2.2
  Using cached createsend-4.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fx46u_6d/createsend/setup.py", line 3, in <module>
        from createsend.createsend import __version__
      File "/tmp/pip-build-fx46u_6d/createsend/createsend/__init__.py", line 20, in <module>
        from createsend.version import __version__
    ImportError: No module named 'createsend.version'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fx46u_6d/createsend/`

Installing 4.2.1 works fine.

**Pull request merged**
