### PR TITLE
Overhall of Project Structure and Setup.py

### PR DESCRIPTION
**Pull request by djstein**
To finally get over the issues with requirements not being installed I have rewritten the project's setup.py to ensure that all requirements are installed prior to operations beginning. To do this I had to rework the structure of the application. All these problems occur because the overall structure of the application realize on all modules being imported in an __init__.py 

This is working for my purposes via this GitHub branch and can be installed in a separate project's requirements.txt by adding: git+git://github.com/getbento/createsend-python.git

### CODE REVIEW

**Comment by djstein** [comment]
this addition will not break imports for Python 2

**Comment by IlyaSukhanov** [comment]
@djstein thank you, with this change library works for me in python 3.6.

Can't wait for Campaign monitor to release this change officially.

**Comment by jdennes** [comment]
This was merged via https://github.com/campaignmonitor/createsend-python/pull/48.

**Comment by jdennes** [comment]
There are still publishing issues which I won't be able to deal with. See https://github.com/campaignmonitor/createsend-python/issues/50.

**Pull request closed without merging**
