### PR TITLE
Support Unicode when decoding json responses from createsend API

### LINKED ISSUE #37: Support unicode in json_to_py
We have some custom fields on one of our lists that use unicode characters specifically the sign for british pounds (£). These cause a unicode decode error when trying to load the custom fields in the python api ( python 2.7 ) 

the error is in the utils.py:

https://github.com/campaignmonitor/createsend-python/blob/master/createsend/utils.py#L109

### PR DESCRIPTION
**Pull request by bharling**
This fixes #37

### CODE REVIEW

**Comment by tobio** [comment]
@bharling are you able to include a test case for this issue as well please?

**Comment by bharling** [comment]
sure - will try and do one today

**Comment by bharling** [comment]
I'll put in a test case for my specific issue, however this modification affects a very hot code path so I'm not sure whether more tests should be conceived?

**Comment by tobio** [comment]
Looks good, much appreciated. Definitely room for more complete testing here, but this is pretty clear for these changes.

**Pull request merged**
